services:
  goserver-test:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .test.env
    ports:
      - '${SERVER_PORT}:8000'
    networks:
      - test_network
    depends_on:
      postgres-test:
        condition: service_healthy
      redis-test:
        condition: service_healthy
      migrate-test:
        condition: service_completed_successfully
      
    command: go test ./...

  postgres-test:
    image: postgres:18.1
    restart: unless-stopped
    env_file: .test.env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_USER_PWD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - dbdata-test:/data/db
    networks:
      - test_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$DB_NAME"]
      interval: 3s
      timeout: 3s
      retries: 10
  
  migrate-test:
    image: migrate/migrate
    env_file: .test.env
    volumes:
      - ./migrations:/migrations
    networks:
      - test_network
    depends_on:
      postgres-test:
        condition: service_healthy
    command:
      [
        "-path", "/migrations",
        "-database", "postgres://${DB_USER}:${DB_USER_PWD}@postgres-test:5432/${DB_NAME}?sslmode=disable",
        "up"
      ]

  redis-test:
    image: redis:8.4.0
    restart: unless-stopped
    env_file: .test.env
    command: redis-server --bind 0.0.0.0 --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
    volumes:
      - cache-test:/data/cache
    networks:
      - test_network
    healthcheck:
      test: ["CMD-SHELL", "redis-cli -a ${REDIS_PASSWORD} ping | grep PONG"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  dbdata-test:
  cache-test:
    driver: local

networks:
  test_network:
    internal: true